_wandb:
    value:
        cli_version: 0.21.0
        e:
            5tcd07ny0pgqpqc5u25njfqvkn2dufpj:
                cpu_count: 192
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "607441125376"
                        used: "39645130752"
                email: memo.ozdincer@mail.utoronto.ca
                executable: /project/rrg-aspuru/memoozd/ts-tools/.venv/bin/python3
                git:
                    commit: d8d05411519d0d5cc0e36f4da3bfe8d4a24df1e7
                    remote: https://github.com/memo-ozdincer/ts-tools
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-17771244-cd33-8b11-8575-f4d4659bfa4c
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-16169e89-0543-f4a3-87c0-58bf6d5347a9
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-999fde4b-32b9-a14e-13cd-8c9d64e3cb4f
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-c2bac0a7-caf1-1e4b-7031-a4855138c7d3
                host: trig-login01
                memory:
                    total: "811262808064"
                os: Linux-5.14.0-570.52.1.el9_6.x86_64-x86_64-AMD_EPYC_9654_96-Core_Processor-with-glibc2.37
                program: <stdin>
                python: CPython 3.11.5
                root: /project/rrg-aspuru/memoozd/ts-tools
                slurm:
                    conf: /opt/slurm/etc/slurm.conf
                    export_env: ALL
                startedAt: "2026-01-16T19:55:07.967437Z"
                writerId: 5tcd07ny0pgqpqc5u25njfqvkn2dufpj
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 15
            "4": 3.11.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
